project:
  type: website
  output-dir: docs

website:
  title: "Statistics, yup!"
  site-url: https://www.statsyup.org/
  description: "This is Simon Schwab's personal website on statistics and data science."
  search: false
  open-graph: true
  favicon: images/logo-96.png
  navbar:
    title: false
    logo: "images/statsyup.png"
    logo-alt: "A donut chart with Statistics, yup! positioned to its right."
    left:
      - href: index.qmd
        text: Bio
      - href: projects.qmd
        text: Projects
      - href: output.qmd
        text: Output
      - href: posts.qmd
        text: Posts
      - href: library.qmd
        text: Library
    right:
      - href: about.qmd
        text: About
  page-footer:
    right: ""
    left: 'Â© 2024--2026 Simon Schwab'
  google-analytics:
    tracking-id: "G-GPR2YZSX56"
    anonymize-ip: true
      
format:
  html:
    theme:
      - cosmo
      - statsyup.scss
    toc: true
    link-external-icon: true
    link-external-newwindow: true